version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: weekly
      time: "13:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5
  
  - package-ecosystem: "gradle"
    directory: "/android"
    schedule:
      interval: weekly
      time: "13:15"
      timezone: Asia/Shanghai
  
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: "13:30"
