targets:
  $default:
    builders:
      freezed:
        generate_for:
          - lib/network/model/**.dart
        options:
          copyWith: false
          equal: false
          toJson: false
          to_string: false
      go_router_builder:
        generate_for:
          include:
            - lib/navigation/router.dart
      json_serializable:
        options:
          checked: true
          explicit_to_json: true
      retrofit_generator:
        generate_for:
          include:
            - lib/network/retrofit/retrofit_network.dart