targets:
  $default:
    builders:
      freezed:
        generate_for:
          - lib/network/model/**.dart
        options:
          copyWith: false
          equal: false
          generic_argument_factories: true
          toJson: false
          to_string: false
          union_value_case: snake
      go_router_builder:
        generate_for:
          include:
            - lib/navigation/router.dart
      injectable_generator:
        generate_for:
          exclude:
            - lib/routing/*.dart
      json_serializable:
        generate_for:
          include:
            - lib/bili/search_type.dart
            - lib/network/retrofit/api_result.dart
            - lib/network/model/**.dart
        options:
          create_to_json: false
          checked: true
          explicit_to_json: true
          field_rename: snake
      chopper_generator:
        generate_for:
          include:
            - lib/network/retrofit/retrofit_network.dart