name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  flutter_test:
    name: Run Flutter Test
    runs-on: ubuntu-latest
    
    timeout-minutes: 60
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
      
      - run: flutter pub get
      - run: flutter --version
      - run: flutter analyze --no-fatal-infos --no-fatal-warnings
      - run: flutter test

  build_iOSApp:
    name: Build Flutter App (iOS)
    needs: [flutter_test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
      
      - run: flutter pub get
      
      - run: flutter clean
      
      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload

      - name: Upload IPA as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app.ipa
          retention-days: 5
          if-no-files-found: warn

  build_androidApk:
    name: Build Flutter App (Android)
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - run: flutter pub get
      
      - run: flutter clean
      
      - run: flutter build apk --debug
      
      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app.apk
          path: 'build/app/outputs/apk/debug/*'
          retention-days: 5
          if-no-files-found: warn
