name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  flutter_test:
    name: Run Flutter Test
    runs-on: ubuntu-latest
    
    timeout-minutes: 60
    
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: stable
          flutter-version-file: pubspec.yaml
      - run: flutter pub get
      
      - name: Build_runner
        run: dart run build_runner build \
          --delete-conflicting-outputs \
          --verbose

      - name: Analyzer
        uses: invertase/github-action-dart-analyzer@v3
        with:
          fatal-infos: false
          fatal-warnings: false

      - run: flutter doctor

      - run: flutter test

  build_iOSApp:
    name: Build Flutter App (iOS)
    needs: [flutter_test]
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
      - run: flutter pub get
      
      - name: Run build_runner
        run: dart run build_runner build \
          --delete-conflicting-outputs \
          --verbose

      - run: pod repo update
        working-directory: ios
      
      - name: Build IPA
        env:
          SENTRY_DSN: ${{secrets.SENTRY_DSN}}
        run: |
          flutter build ios \
            --release
            --no-codesign \
            --dart-define=SENTRY_DSN="$SENTRY_DSN" \
            --verbose
          mkdir -p Payload
          mv ./build/ios/iphoneos/Runner.app Payload
          zip -r -y Payload.zip Payload/Runner.app
          mv Payload.zip Payload.ipa

      - name: Upload IPA as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: Payload.ipa
