name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  flutter_test:
    name: Run Flutter Test
    runs-on: ubuntu-latest
    
    timeout-minutes: 60
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: stable
      - run: flutter pub get
      
      - name: Run build_runner
        run: dart run build_runner build --delete-conflicting-outputs --verbose

      - uses: invertase/github-action-dart-analyzer@v3
        with:
          fatal-infos: false
          fatal-warnings: false

      - run: flutter test

  build_iOSApp:
    name: Build Flutter App (iOS)
    needs: [flutter_test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: stable
          flutter-version-file: pubspec.yaml
      - run: flutter pub get
      
      - name: Run build_runner
        run: dart run build_runner build --delete-conflicting-outputs --verbose

      - run: flutter clean
      
      - run: |
          flutter build ios --no-codesign
          ln -sf ./build/ios/iphoneos Payload
          zip -r app.ipa Payload

      - name: Upload IPA as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app.ipa
          path: app.ipa
          retention-days: 5
          if-no-files-found: warn
